ALTER TABLE purchase_items
  ADD COLUMN batch_no VARCHAR(100),
  ADD COLUMN expiry_date DATE,
  ADD COLUMN mfg_date DATE,
  ADD COLUMN mrp NUMERIC(12, 2) NOT NULL DEFAULT 0,
  ADD COLUMN unit VARCHAR(50),
  ADD COLUMN gst_rate NUMERIC(5, 2) NOT NULL DEFAULT 0,
  ADD COLUMN gst_amount NUMERIC(12, 2) NOT NULL DEFAULT 0;
